"""add_printer.

Revision ID: a1b2c3d4e5f6
Revises: 415a8f855e14
Create Date: 2024-06-01 12:00:00.000000
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "415a8f855e14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "printer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("registered", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("spool_id", sa.Integer(), sa.ForeignKey("spool.id"), nullable=True, unique=True),
        sa.Column("comment", sa.String(length=1024), nullable=True),
        sa.Column("external_id", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_printer_id"), "printer", ["id"], unique=False)

    op.create_table(
        "printer_field",
        sa.Column("printer_id", sa.Integer(), sa.ForeignKey("printer.id"), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("printer_id", "key"),
    )
    op.create_index(op.f("ix_printer_field_printer_id"), "printer_field", ["printer_id"], unique=False)
    op.create_index(op.f("ix_printer_field_key"), "printer_field", ["key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_printer_field_key"), table_name="printer_field")
    op.drop_index(op.f("ix_printer_field_printer_id"), table_name="printer_field")
    op.drop_table("printer_field")
    op.drop_index(op.f("ix_printer_id"), table_name="printer")
    op.drop_table("printer")
    # ### end Alembic commands ###
